import { FirebaseCollege } from '@/lib/firebase';

type CollegeData = Omit<FirebaseCollege, 'id'>;

// Gujarat colleges data organized by districts
export const gujaratColleges: CollegeData[] = [
  // Ahmedabad District
  {
    name: "Gujarat University",
    location: "Ahmedabad",
    district: "Ahmedabad",
    type: "Government",
    website: "https://www.gujaratuniversity.ac.in",
    contactInfo: "+91-79-26300164",
    courses: ["Arts", "Science", "Commerce", "Law", "Management"],
    description: "One of the oldest and prestigious universities in Gujarat, established in 1949.",
  },
  {
    name: "Ahmedabad University",
    location: "Ahmedabad",
    district: "Ahmedabad",
    type: "Private",
    website: "https://ahduni.edu.in",
    contactInfo: "+91-79-61911000",
    courses: ["Engineering", "Management", "Arts", "Sciences"],
    description: "A private, non-profit university established in 2009 offering a liberal education.",
  },
  {
    name: "CEPT University",
    location: "Ahmedabad",
    district: "Ahmedabad",
    type: "Private",
    website: "https://cept.ac.in",
    contactInfo: "+91-79-26302470",
    courses: ["Architecture", "Planning", "Technology", "Design"],
    description: "Premier institution focused on understanding, designing, planning, and managing human habitats.",
  },
  {
    name: "L.D. College of Engineering",
    location: "Ahmedabad",
    district: "Ahmedabad",
    type: "Government",
    website: "https://ldce.ac.in",
    contactInfo: "+91-79-26302887",
    courses: ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Computer Engineering"],
    description: "One of the oldest engineering colleges in Gujarat established in 1948.",
  },
  {
    name: "Gujarat Technological University",
    location: "Ahmedabad",
    district: "Ahmedabad",
    type: "Government",
    website: "https://gtu.ac.in",
    contactInfo: "+91-79-23267521",
    courses: ["Engineering", "Pharmacy", "Management", "Computer Applications"],
    description: "State university providing technological education established in 2007.",
  },
  
  // Vadodara District
  {
    name: "Maharaja Sayajirao University of Baroda",
    location: "Vadodara",
    district: "Vadodara",
    type: "Government",
    website: "https://msubaroda.ac.in",
    contactInfo: "+91-265-2795555",
    courses: ["Arts", "Science", "Commerce", "Engineering", "Fine Arts"],
    description: "Founded in 1949, it's one of the premier universities in India.",
  },
  {
    name: "Faculty of Technology and Engineering, MSU",
    location: "Vadodara",
    district: "Vadodara",
    type: "Government",
    website: "https://msubaroda.ac.in/faculty/Technology-Engineering",
    contactInfo: "+91-265-2434188",
    courses: ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Computer Engineering"],
    description: "Engineering faculty of Maharaja Sayajirao University offering technical education.",
  },
  {
    name: "Parul University",
    location: "Vadodara",
    district: "Vadodara",
    type: "Private",
    website: "https://paruluniversity.ac.in",
    contactInfo: "+91-2668-260300",
    courses: ["Engineering", "Medicine", "Pharmacy", "Management", "Law"],
    description: "Private university offering diverse programs across multiple disciplines.",
  },
  
  // Rajkot District
  {
    name: "Saurashtra University",
    location: "Rajkot",
    district: "Rajkot",
    type: "Government",
    website: "https://saurashtrauniversity.edu",
    contactInfo: "+91-281-2578501",
    courses: ["Arts", "Science", "Commerce", "Law", "Engineering"],
    description: "Established in 1967 to serve the educational needs of the Saurashtra region.",
  },
  {
    name: "V.V.P. Engineering College",
    location: "Rajkot",
    district: "Rajkot",
    type: "Government-Aided",
    website: "https://vvpedulink.ac.in",
    contactInfo: "+91-281-2783394",
    courses: ["Mechanical Engineering", "Computer Engineering", "Electrical Engineering", "Civil Engineering"],
    description: "Engineering college affiliated with GTU offering technical education since 1996.",
  },
  {
    name: "Marwadi University",
    location: "Rajkot",
    district: "Rajkot",
    type: "Private",
    website: "https://marwadiuniversity.ac.in",
    contactInfo: "+91-281-2924154",
    courses: ["Engineering", "Science", "Commerce", "Law", "Management"],
    description: "Private university established in 2016 offering various undergraduate and postgraduate programs.",
  },
  
  // Gandhinagar District
  {
    name: "Indian Institute of Technology Gandhinagar",
    location: "Gandhinagar",
    district: "Gandhinagar",
    type: "Government",
    website: "https://iitgn.ac.in",
    contactInfo: "+91-79-23952000",
    courses: ["Engineering", "Sciences", "Humanities"],
    description: "One of India's premier engineering institutions established in 2008.",
  },
  {
    name: "DAIICT",
    location: "Gandhinagar",
    district: "Gandhinagar",
    type: "Private",
    website: "https://daiict.ac.in",
    contactInfo: "+91-79-30510500",
    courses: ["Information & Communication Technology", "Computer Science", "Electronics"],
    description: "Dhirubhai Ambani Institute of Information and Communication Technology founded in 2001.",
  },
  {
    name: "PDPU (Pandit Deendayal Energy University)",
    location: "Gandhinagar",
    district: "Gandhinagar",
    type: "Private",
    website: "https://pdpu.ac.in",
    contactInfo: "+91-79-23275060",
    courses: ["Engineering", "Management", "Liberal Studies", "Petroleum Engineering"],
    description: "University focusing on energy education and research established in 2007.",
  },
  {
    name: "Gujarat National Law University",
    location: "Gandhinagar",
    district: "Gandhinagar",
    type: "Government",
    website: "https://gnlu.ac.in",
    contactInfo: "+91-79-23276611",
    courses: ["Law", "Legal Studies"],
    description: "Premier law university established in 2003 offering undergraduate and postgraduate legal education.",
  },
  
  // Surat District
  {
    name: "Veer Narmad South Gujarat University",
    location: "Surat",
    district: "Surat",
    type: "Government",
    website: "https://vnsgu.ac.in",
    contactInfo: "+91-261-2227141",
    courses: ["Arts", "Science", "Commerce", "Law", "Management"],
    description: "Established in 1965, serving the educational needs of South Gujarat region.",
  },
  {
    name: "Sarvajanik College of Engineering and Technology",
    location: "Surat",
    district: "Surat",
    type: "Government-Aided",
    website: "https://scet.ac.in",
    contactInfo: "+91-261-2240146",
    courses: ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Computer Engineering"],
    description: "Engineering college established in 1995 offering technical education.",
  },
  {
    name: "SVNIT (Sardar Vallabhbhai National Institute of Technology)",
    location: "Surat",
    district: "Surat",
    type: "Government",
    website: "https://svnit.ac.in",
    contactInfo: "+91-261-2201646",
    courses: ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Computer Engineering"],
    description: "One of the premier engineering institutions in India established in 1961.",
  },
  
  // Bhavnagar District
  {
    name: "Maharaja Krishnakumarsinhji Bhavnagar University",
    location: "Bhavnagar",
    district: "Bhavnagar",
    type: "Government",
    website: "https://mkbhavuni.edu.in",
    contactInfo: "+91-278-2426519",
    courses: ["Arts", "Science", "Commerce", "Management"],
    description: "State university established in 1978 serving the Bhavnagar region.",
  },
  {
    name: "Government Engineering College, Bhavnagar",
    location: "Bhavnagar",
    district: "Bhavnagar",
    type: "Government",
    website: "https://gecbh.cteguj.in",
    contactInfo: "+91-278-2516721",
    courses: ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Computer Engineering"],
    description: "Government engineering college offering technical education.",
  },
  
  // Mehsana District
  {
    name: "Ganpat University",
    location: "Mehsana",
    district: "Mehsana",
    type: "Private",
    website: "https://ganpatuniversity.ac.in",
    contactInfo: "+91-2762-226000",
    courses: ["Engineering", "Pharmacy", "Management", "Computer Applications"],
    description: "Private university established in 2005 offering various programs.",
  },
  {
    name: "Government Engineering College, Mehsana",
    location: "Mehsana",
    district: "Mehsana",
    type: "Government",
    website: "https://gecmehsana.ac.in",
    contactInfo: "+91-2762-222914",
    courses: ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Computer Engineering"],
    description: "Government engineering college affiliated with GTU.",
  },
  
  // Junagadh District
  {
    name: "Junagadh Agricultural University",
    location: "Junagadh",
    district: "Junagadh",
    type: "Government",
    website: "https://jau.in",
    contactInfo: "+91-285-2670194",
    courses: ["Agriculture", "Veterinary", "Fisheries", "Agricultural Engineering"],
    description: "Agricultural university established in 2004 focused on agricultural education and research.",
  },
  {
    name: "Government Engineering College, Junagadh",
    location: "Junagadh",
    district: "Junagadh",
    type: "Government",
    website: "https://gecjunagadh.ac.in",
    contactInfo: "+91-285-2660150",
    courses: ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Computer Engineering"],
    description: "Government engineering college offering technical education.",
  },
  
  // Anand District
  {
    name: "Anand Agricultural University",
    location: "Anand",
    district: "Anand",
    type: "Government",
    website: "https://aau.in",
    contactInfo: "+91-2692-261273",
    courses: ["Agriculture", "Dairy Technology", "Food Technology", "Agricultural Engineering"],
    description: "Agricultural university established in 2004 with focus on dairy and food technology.",
  },
  {
    name: "Charotar University of Science and Technology",
    location: "Anand",
    district: "Anand",
    type: "Private",
    website: "https://charusat.ac.in",
    contactInfo: "+91-2697-265011",
    courses: ["Engineering", "Pharmacy", "Management", "Computer Applications"],
    description: "Private university established in 2009 offering education in science and technology.",
  },
  
  // Jamnagar District
  {
    name: "Gujarat Ayurved University",
    location: "Jamnagar",
    district: "Jamnagar",
    type: "Government",
    website: "https://ayurveduniversity.edu.in",
    contactInfo: "+91-288-2555566",
    courses: ["Ayurvedic Medicine", "Ayurvedic Pharmacy", "Panchakarma"],
    description: "First statutory Ayurved University in the world established in 1965.",
  },
  {
    name: "Shri G.H. Patel College of Engineering and Technology",
    location: "Vallabh Vidyanagar, Anand",
    district: "Anand",
    type: "Government-Aided",
    website: "https://gcet.ac.in",
    contactInfo: "+91-2692-231611",
    courses: ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Computer Engineering"],
    description: "Engineering college established in 1996 affiliated with GTU.",
  },
  
  // Kutch District
  {
    name: "Krantiguru Shyamji Krishna Verma Kachchh University",
    location: "Bhuj",
    district: "Kutch",
    type: "Government",
    website: "https://kskvku.digitaluniversity.ac",
    contactInfo: "+91-2832-235001",
    courses: ["Arts", "Science", "Commerce", "Education"],
    description: "State university established in 2003 serving the Kutch region.",
  },
  {
    name: "Government Engineering College, Bhuj",
    location: "Bhuj",
    district: "Kutch",
    type: "Government",
    website: "https://gecbhuj.ac.in",
    contactInfo: "+91-2832-223941",
    courses: ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Computer Engineering"],
    description: "Government engineering college offering technical education in Kutch region.",
  },
];

// You can use gujaratColleges array with addMultipleColleges function to populate Firestore